<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>DesktopBaskets</AssemblyName>
    <Version>0.4.6</Version>
    <ApplicationIcon>Assets\DesktopBaskets.ico</ApplicationIcon>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/src/DesktopBaskets</PathMap>
    <NoWarn>NETSDK1138</NoWarn>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Newtonsoft.Json" Version="13.0.3" /><Using Remove="System.Net.Http" /></ItemGroup>
  <ItemGroup><Content Include="Assets\*"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup>
</Project>
